export enum TARGET_NAME {
  INPAGE = 'qrypto-inpage',
  CONTENTSCRIPT = 'qrypto-contentscript',
  BACKGROUND = 'qrypto-background',
}

export enum PORT_NAME {
  POPUP = 'qrypto-popup',
  CONTENTSCRIPT = 'qrypto-contentscript',
}

export enum RPC_METHOD {
  SEND_TO_CONTRACT = 'sendToContract',
  CALL_CONTRACT = 'callContract',
}

export enum API_TYPE {
  SIGN_TX_URL_RESOLVED,
  RPC_REQUEST,
  RPC_RESONSE,
  RPC_SEND_TO_CONTRACT,
  RPC_CALL_CONTRACT,
  TRANSACTION_APPROVED,
}

export enum MESSAGE_TYPE {
  ROUTE_LOGIN,
  RESTORE_SESSION,
  LOGIN,
  LOGIN_SUCCESS_WITH_ACCOUNTS,
  LOGIN_SUCCESS_NO_ACCOUNTS,
  LOGIN_FAILURE,
  CREATE_WALLET,
  SAVE_TO_FILE,
  IMPORT_MNEMONIC,
  IMPORT_MNEMONIC_FAILURE,
  ACCOUNT_LOGIN,
  ACCOUNT_LOGIN_SUCCESS,
  START_TX_POLLING,
  STOP_TX_POLLING,
  GET_MORE_TXS,
  GET_TXS_RETURN,
  SEND_TOKENS,
  SEND_TOKENS_SUCCESS,
  SEND_TOKENS_FAILURE,
  SEND_QRC_TOKENS,
  QRC_TOKENS_RETURN,
  ADD_TOKEN,
  REMOVE_TOKEN,
  LOGOUT,
  CHANGE_NETWORK,
  CHANGE_NETWORK_SUCCESS,
  EXTERNAL_RAW_CALL,
  EXTERNAL_SEND_TO_CONTRACT,
  EXTERNAL_CALL_CONTRACT,
  EXTERNAL_RPC_CALL_RETURN,
  SAVE_SESSION_LOGOUT_INTERVAL,
  GET_NETWORKS,
  GET_NETWORK_INDEX,
  GET_NETWORK_EXPLORER_URL,
  GET_ACCOUNTS,
  GET_LOGGED_IN_ACCOUNT_NAME,
  GET_WALLET_INFO,
  GET_WALLET_INFO_RETURN,
  GET_QTUM_USD,
  GET_QTUM_USD_RETURN,
  GET_QRC_TOKEN_LIST,
  GET_SESSION_LOGOUT_INTERVAL,
  IS_MAINNET,
  HAS_ACCOUNTS,
  VALIDATE_WALLET_NAME,
  GET_QRC_TOKEN_DETAILS,
  QRC_TOKEN_DETAILS_RETURN,
}

export enum RESPONSE_TYPE {
  RESTORING_SESSION,
}

export enum STORAGE {
  APP_SALT = 'appSalt',
  TESTNET_ACCOUNTS = 'testnetAccounts',
  MAINNET_ACCOUNTS = 'mainnetAccounts',
  LOGGED_IN_ACCOUNT = 'loggedInAccount',
  NETWORK_INDEX = 'networkIndex',
  ACCOUNT_TOKEN_LIST = 'accountTokenList',
}

export enum SEND_STATE {
  INITIAL = 'Confirm',
  SENDING = 'Sending...',
  SENT = 'Sent!',
}

export enum NETWORK_NAMES {
  TESTNET = 'TestNet',
  MAINNET = 'MainNet',
}

export enum INTERVAL_NAMES {
  NONE = 'None',
  ONE_MIN = '1 min',
  TEN_MIN = '10 min',
  THIRTY_MIN = '30 min',
  TWO_HOUR = '2 hr',
  TWELVE_HOUR = '12 hr',
}
